### ISSUE TITLE
字体（font-family）出现在多个文件中。不利于更改，且冲突

### ISSUE THREAD

**Issue by Tedko** [Jisuanke/jisuanke-UI#18]
分别在

```
_typography.scss
```

（并没有什么ruan用，没有编译成 site.min.css）
以及

```
jisuanke-UI/css/bootstrap.min.css
```

此处不应该指定字体，因为 min.css 难以删改

```
site.css
```

也出现了字体。

gruntfile 中：

```
dist: {
        files: {
          'css/site.min.css': [
            'css/bootstrap.min.css',
            '<%= meta.defaultPath %>/css/<%= pkg.name %>.css',
            'css/site.css',
            'css/jsTreeStyle.min.css'
          ],
          '<%= meta.defaultPath %>/css/<%= pkg.name %>.min.css': '<%= meta.defaultPath %>/css/<%= pkg.name %>.css'
        }
      }

```

所以 bootstrap.min.css 中不应该保留字体，否则会影响别的地方的字体设置。
切 bootstrap.min.css 中的字体只能影响 body，会造成有地方没有指定中文字体，如下图：

![2015-06-16 11 56 24](https://cloud.githubusercontent.com/assets/6687437/8175653/fb9a2e44-141f-11e5-82df-6326fbe50227.png)

**Comment by Tedko** [comment]
![2015-06-16 3 18 17](https://cloud.githubusercontent.com/assets/6687437/8177814/0dbff71e-143b-11e5-8f35-67e22dce6c5b.png)

尝试更改了

```
css/site.css
```

同时删除了

```
css/bootstr.min.css
```

的字体 font-family 。

在该 repo 的 index 预览起到了作用。同时 site.min.css 也起了变化。

但是在 jisuanke2 中

```
bower update
gulp
```

之后没有起到作用。反而丢失了全部字体，fallback 到 sans-serif

怀疑 jisuanke2 没有用 site.min.css

把 bst.min.css 美化之后
- 更改了字体
- 删除了本来 html 里的 font-family = sans-serif， 解决了h1-6的字体 inherit 到 html

**Comment by JasinYip** [comment]
site.min.css 只是 Jisuanke-UI 展示页用的……

**Comment by ifduyue** [comment]
请**不要修改 bootstrap.min.css**。
多个相同 css selector 下 font-family 规则，后来者胜。我们打包的时候、引用的时候， bootstrap 都是在最前面的。如果对 bootstrap 的规则不满意，请用自己提供的规则覆盖它，而不是修改 bootstrap。
