### ISSUE TITLE
手机端下拉菜单出现问题

### ISSUE THREAD

**Issue by WenryXu** [Jisuanke/jisuanke-UI#21]
![image](https://cloud.githubusercontent.com/assets/3060186/8395754/85f32466-1db6-11e5-8408-591e3ae70d74.png)
长残了……

设置页的就是好的 
![image](https://cloud.githubusercontent.com/assets/3060186/8395759/03c97520-1db7-11e5-9dd2-6876b6ee73a1.png)

**Comment by ouerlianchuang** [comment]
3a16b73e822c50ae999104891dceed4e3aa7c774 fix
