### ISSUE TITLE
修改下拉菜单控件的英文提示语

### ISSUE THREAD

**Issue by WenryXu** [Jisuanke/jisuanke-UI#26]
![image](https://cloud.githubusercontent.com/assets/3060186/8470159/37e10706-20b9-11e5-98f3-fe952bfa1f91.png)
没有找到“XXXX”
![image](https://cloud.githubusercontent.com/assets/3060186/8470169/5e3ec74e-20b9-11e5-8886-ef13106cfa3a.png)
请选择城市名

**Comment by Tedko** [comment]
grep 没找到。这个是 bs 里的？

**Comment by Tedko** [comment]
@ouerlianchuang  这个是 amaze ui的，之前改好了吧？

**Comment by ouerlianchuang** [comment]
已经改成中文啦 @Tedko

**Comment by WenryXu** [comment]
@ouerlianchuang 我都把文案给你写好了……你还自己写……

**Comment by ifduyue** [comment]
@ouerlianchuang 处理之前先把 issue 分配给自己，防止多个人同时处理一件事情。

**Comment by JasinYip** [comment]
提交 commit 或者 pr 时请关联一下 issue

**Comment by WenryXu** [comment]
我记得这个已经搞定了
