### ISSUE TITLE
重做按钮大小问题

### ISSUE THREAD

**Issue by Tedko** [Jisuanke/jisuanke-UI#27]
是不是 fontawesome 那里改了之后的问题？

**Comment by Tedko** [comment]
![2015-07-02 12 02 45](https://cloud.githubusercontent.com/assets/6687437/8459248/89ae118e-204e-11e5-8e43-fbad48ab979b.png)
![2015-07-02 12 02 19](https://cloud.githubusercontent.com/assets/6687437/8459249/89ccc52a-204e-11e5-8122-1fd94a824293.png)

**Comment by ouerlianchuang** [comment]
fix  cd677c0eff118c2cf9ed531eb8f99d6661e5776f
