### ISSUE TITLE
下拉组件、日历组件、输入框的部分颜色修改

### ISSUE THREAD

**Issue by WenryXu** [Jisuanke/jisuanke-UI#29]
# 很重要的一个色值：`@darkgray-dark`
### guide 页（姓名、密码、简介）

![image](https://cloud.githubusercontent.com/assets/3060186/8494815/118efb48-219b-11e5-99c8-d0a1392b766e.png)

![image](https://cloud.githubusercontent.com/assets/3060186/8494275/e496e952-2195-11e5-9c1b-aedda5c9f75b.png)

将这一部分色值为 `#96A0AD` 的外边框的颜色改为 `@darkgray-dark`
### guide 页、basic 页（生日）

![image](https://cloud.githubusercontent.com/assets/3060186/8494839/3fadf524-219b-11e5-9f64-e29964f2d53c.png)

![image](https://cloud.githubusercontent.com/assets/3060186/8494650/59d4d456-2199-11e5-8ee3-3db5df04e761.png)

将这一部分色值为 `#96A0AD` 的外边框的颜色改为 `@darkgray-dark`
### 下拉菜单中的选中项的底色

![image](https://cloud.githubusercontent.com/assets/3060186/8494706/f2652342-2199-11e5-9bd4-bb663d36a0b6.png)

将这一部分色值为 `#607D8B` 的底色颜色改为 `@darkgray-dark`
### 下拉菜单中展开部分的边框颜色

![image](https://cloud.githubusercontent.com/assets/3060186/8494762/af418a32-219a-11e5-8efe-b2d73469aa10.png)

![image](https://cloud.githubusercontent.com/assets/3060186/8494782/cafa92c8-219a-11e5-992d-b54ed4fc64c5.png)

将这一部分色值为 `#BBBBBB` 的外边框的颜色改为 `@darkgray-dark`

**Comment by WenryXu** [comment]
我只能通过页面取色来找到它们了，表示并不能定位到在代码的哪个位置 TAT

**Comment by Tedko** [comment]
取色方法的问题。Mac 下推荐 「Color Snipper2」
