### ISSUE TITLE
下拉菜单中标签样式修改

### ISSUE THREAD

**Issue by WenryXu** [Jisuanke/jisuanke-UI#30]
就是这里面的标签
![image](https://cloud.githubusercontent.com/assets/3060186/8742228/b35aa3fa-2c95-11e5-9938-4094c017395c.png)

使用咱们已有的标准样式：
![image](https://cloud.githubusercontent.com/assets/3060186/8742232/c4b29e82-2c95-11e5-885a-2c273482da82.png)

**Comment by JasinYip** [comment]
貌似看起来像是难题筛选器那边的~不过 `border-radius` 可能需要改一下
![image](https://cloud.githubusercontent.com/assets/7105264/8769157/bc3fe680-2ec8-11e5-994f-65ebfa196f52.png)

**Comment by WenryXu** [comment]
难题筛选器这个竟然用的是 badge 而不是 label……应该用 label 才对 = =
