### ISSUE TITLE
工具提示条三角存在响应不完备

### ISSUE THREAD

**Issue by haoranyu** [Jisuanke/jisuanke-UI#4]
工具提示条的配套小三角现在存在响应不完备的情况，出现了一些接缝，如下：
![image](https://cloud.githubusercontent.com/assets/2560088/5789434/a5ba0d54-9ea5-11e4-97d4-a477802c227f.png)

![image](https://cloud.githubusercontent.com/assets/2560088/5789435/b103e18a-9ea5-11e4-9603-883a57b3c0a4.png)

![image](https://cloud.githubusercontent.com/assets/2560088/5789437/b74baf96-9ea5-11e4-951b-4f028b9a01f0.png)

需要修复

**Comment by ouerlianchuang** [comment]
改变浏览器窗口大小未发现此问题  百分比调整页面状态下 .tooltip-arrow的border-width 改成6 会解决这个bug

**Comment by haoranyu** [comment]
确认为单一case，难以在其他设备复现。
