### ISSUE TITLE
表单输入框高度存在问题

### ISSUE THREAD

**Issue by haoranyu** [Jisuanke/jisuanke-UI#5]
输入框的部分多了两个像素的高度
![image](https://cloud.githubusercontent.com/assets/2560088/5789439/db82bec2-9ea5-11e4-9131-64f0f16092a8.png)

![image](https://cloud.githubusercontent.com/assets/2560088/5789442/e19c8950-9ea5-11e4-93d2-93889e2f9371.png)

需要修复

**Comment by ouerlianchuang** [comment]
改变浏览器窗口大小未发现此问题,,只会在百分比放大下出现；确认为单一case
