### ISSUE TITLE
时间线小三角存在接缝

### ISSUE THREAD

**Issue by haoranyu** [Jisuanke/jisuanke-UI#6]
如图所示，类似于提示工具条的问题
![image](https://cloud.githubusercontent.com/assets/2560088/5789454/1fea89e6-9ea6-11e4-96c6-e9099312e0f3.png)
![image](https://cloud.githubusercontent.com/assets/2560088/5789455/23cd8b8a-9ea6-11e4-8a73-5fd8f86ca6be.png)
有待修正

**Comment by ouerlianchuang** [comment]
改变浏览器窗口大小未发现此问题,,只会在百分比放大下出现；确认为单一case
